### ISSUE TITLE
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by rabintang** [Integration-Automation/ReEdgeGPT#135]
Hello, can you help me to see what the problem is?

`Bot:
Traceback (most recent call last):
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/re_edge_gpt/__main__.py", line 248, in <module>
    main()
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/re_edge_gpt/__main__.py", line 244, in main
    asyncio.run(async_main(args))
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/re_edge_gpt/__main__.py", line 128, in async_main
    await bot.ask(
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/re_edge_gpt/chat/re_edge_gpt.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/re_edge_gpt/chat/chathub.py", line 103, in ask_stream
    wss = await self.aio_session.ws_connect(
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/client.py", line 825, in _ws_connect
    resp = await self.request(
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/connector.py", line 909, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/connector.py", line 1307, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/rabintang/miniconda3/envs/aigc/lib/python3.10/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x109871030>`

**Comment by JE-Chen** [comment]
Just a aiohttp warning: when you no longer want to use the bot, you need to call bot.close().

**Comment by JE-Chen** [comment]
If you are using Jupyter, you need to install nest_asyncio and call nest_asyncio.apply() before calling every asyncio function.

**Comment by rabintang** [comment]
thank you for you quick response! i run it by command line, not python code. for i'm new in Network area, may you tell me detail steps? thank you!
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/3820920/a7dd8cd5-4d3b-4f42-b0e2-182a7ee688c0)

**Comment by JE-Chen** [comment]
Please use code to run ReEdgeGPT now, I will fix command line bot this weekend.

**Comment by JE-Chen** [comment]
> thank you for you quick response! i run it by command line, not python code. for i'm new in Network area, may you tell me detail steps? thank you! ![image](https://private-user-images.githubusercontent.com/3820920/322679335-a7dd8cd5-4d3b-4f42-b0e2-182a7ee688c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTcyMzcsIm5iZiI6MTcxMzI1NjkzNywicGF0aCI6Ii8zODIwOTIwLzMyMjY3OTMzNS1hN2RkOGNkNS00ZDNiLTRmNDItYjBlMi0xODJhN2VlNjg4YzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMDg0MjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjEyNzM5MTAxNzFlYWZkYjNiYjJhYjYyMDFiZDU5MzhjMzE5YjQ3ZjQ5ZDcyMjJiYmRhMTEwYTAzZjY3M2I1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bqqi0-yKj0p_re81YGb8uXfmbvHvA2nDKMMOXvjeKLk)

And I check this error, look like your proxy service provider close the connection.

**Comment by JE-Chen** [comment]
![image](https://github.com/Integration-Automation/ReEdgeGPT/assets/33644111/3c13e446-3d7a-4e9f-8897-0901d6c6e4f6)
I can run command line bot without using proxy service

**Comment by rabintang** [comment]
thanks for your response! when i run in a USA server, then it works! i may be the problem of the proxy, as you say.
