### ISSUE TITLE
image create error

### ISSUE THREAD

**Issue by FuseFairy** [Integration-Automation/ReEdgeGPT#145]
Recently, this error occurs when generating images, tried using VPN and changing accounts, but it's still the same.

package version: 0.0.39
```
Traceback (most recent call last):
  File "c:\Users\ASUS\python project\discord bot EdgeGPT\src\image\image_create.py", line 73, in create_image_bing
    images = await async_gen.get_images(prompt=prompt, timeout=int(os.getenv("IMAGE_TIMEOUT")), max_generate_time_sec=int(os.getenv("IMAGE_MAX_CREATE_SEC")))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\Lib\site-packages\re_edge_gpt\image\image_genearation.py", line 320, in get_images
    raise ImageCreateFailed(error_image_create_failed)
re_edge_gpt.utils.exception.exceptions.ImageCreateFailed: Image create failed pls check cookie or old image still creating
```

**Comment by JE-Chen** [comment]
Working fine now; I didn’t change anything. Maybe their service is down, like today.
